### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mundays10** [faiqxid/Chain-Game-Bot#1]
Traceback (most recent call last):
  File "/root/MemeFiBot/venv/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chain/chain.py", line 88, in <module>
    main()
  File "/root/chain/chain.py", line 31, in main
    auth_token = get_new_token(query_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/chain/chain.py", line 26, in get_new_token
    response_data = response.json()
                    ^^^^^^^^^^^^^^^
  File "/root/MemeFiBot/venv/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by faiqxid** [comment]
For the latest update now you have to use query_id instead of using the auth token anymore

**Comment by mundays10** [comment]
not solved 
![image](https://github.com/faiqxid/Chain-Game-Bot/assets/170218820/d94a4162-8f69-4faa-809a-c6eb23627c30)

**Comment by faiqxid** [comment]
Your quer code is wong bro

You can contact me on telegram i will hwlp you 
Tele : @idFaiq
